### ISSUE TITLE
如果用了自适应布局怎么办呢

### ISSUE THREAD

**Issue by Azraeltulips** [mengwang0301/CustomImageTitleButton#1]
如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢

**Comment by mengwang0301** [comment]
> 如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢

没太明白是什么意思, 是用SnapKit为UIbutton添加约束, 然后button获取不到里面的imageview的frame吗?

**Comment by Azraeltulips** [comment]
> > 如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢
> 
> 没太明白是什么意思, 是用SnapKit为UIbutton添加约束, 然后button获取不到里面的imageview的frame吗?

是的，用了约束后就获取不到imageview的frame了

**Comment by mengwang0301** [comment]
> > > 如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢
> > 
> > 
> > 没太明白是什么意思, 是用SnapKit为UIbutton添加约束, 然后button获取不到里面的imageview的frame吗?
> 
> 是的，用了约束后就获取不到imageview的frame了

之前没考虑到SnapKit, 刚更新了一下, 试试. 我这边试了下, 好像没问题.

**Comment by Azraeltulips** [comment]
> > > > 如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢
> > > 
> > > 
> > > 没太明白是什么意思, 是用SnapKit为UIbutton添加约束, 然后button获取不到里面的imageview的frame吗?
> > 
> > 
> > 是的，用了约束后就获取不到imageview的frame了
> 
> 之前没考虑到SnapKit, 刚更新了一下, 试试. 我这边试了下, 好像没问题.

我试过了 不行
let button = CustomImageTitleButton(type: .custom)
        button.setTitle("测试按钮", for: .normal)
        button.setTitleColor(.orange, for: .normal)
        button.setImage(UIImage(named: "pending_section01"), for: .normal)
        button.titleLabel?.font = .systemFont(ofSize: 14)
        button.resetEdgeInsets(type: .topImageBottomTitle, space: 10)
        
        contentView.addSubview(button)
        
        button.snp.makeConstraints { (make) in
            make.width.equalTo(100)
            make.height.equalTo(100)
            make.center.equalToSuperview()
        }

**Comment by mengwang0301** [comment]
> > > > > 如果按钮的布局使用的SnapKit库，会导致获取不到imageView的坐标，要怎么解决呢
> > > > 
> > > > 
> > > > 没太明白是什么意思, 是用SnapKit为UIbutton添加约束, 然后button获取不到里面的imageview的frame吗?
> > > 
> > > 
> > > 是的，用了约束后就获取不到imageview的frame了
> > 
> > 
> > 之前没考虑到SnapKit, 刚更新了一下, 试试. 我这边试了下, 好像没问题.
> 
> 我试过了 不行
> let button = CustomImageTitleButton(type: .custom)
> button.setTitle("测试按钮", for: .normal)
> button.setTitleColor(.orange, for: .normal)
> button.setImage(UIImage(named: "pending_section01"), for: .normal)
> button.titleLabel?.font = .systemFont(ofSize: 14)
> button.resetEdgeInsets(type: .topImageBottomTitle, space: 10)
> 
> ```
>     contentView.addSubview(button)
>     
>     button.snp.makeConstraints { (make) in
>         make.width.equalTo(100)
>         make.height.equalTo(100)
>         make.center.equalToSuperview()
>     }
> ```

pull下, 再试试
